[build]
skip-lint = false

[features]
seeds = false
init-if-needed = false

[programs.devnet]
firststep_sponsorship = "7SJc8nfkddM7uFZJZuAkkM2NBsM7EbCGfD5LPXyYwJ1D"

[programs.mainnet]
firststep_sponsorship = "7SJc8nfkddM7uFZJZuAkkM2NBsM7EbCGfD5LPXyYwJ1D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
